openapi: 3.0.3
info:
  title: Tennis Court Finder API
  description: API for monitoring tennis court availability and sending alerts
  version: 1.0.0
  contact:
    name: Tennis Court Finder Team
    email: support@tenniscourtfinder.com

servers:
  - url: http://localhost:8000
    description: Development server
  - url: https://api.tenniscourtfinder.com
    description: Production server

paths:
  /health:
    get:
      summary: Health check endpoint
      description: Returns the health status of the API
      operationId: health_check
      responses:
        '200':
          description: API is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "healthy"
                  timestamp:
                    type: string
                    format: date-time
                    example: "2024-01-15T10:30:00Z"

  /clubs:
    get:
      summary: Get available tennis clubs
      description: Returns a list of tennis clubs that can be monitored
      operationId: get_tennis_clubs
      responses:
        '200':
          description: List of tennis clubs
          content:
            application/json:
              schema:
                type: object
                properties:
                  clubs:
                    type: array
                    items:
                      $ref: '#/components/schemas/TennisClub'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /clubs/{club_id}/availability:
    get:
      summary: Get court availability for a specific club
      description: Returns available court times for a specific tennis club
      operationId: get_club_availability
      parameters:
        - name: club_id
          in: path
          required: true
          schema:
            type: string
          description: Unique identifier for the tennis club
        - name: date
          in: query
          required: false
          schema:
            type: string
            format: date
          description: Date to check availability (defaults to today)
      responses:
        '200':
          description: Court availability information
          content:
            application/json:
              schema:
                type: object
                properties:
                  club_id:
                    type: string
                  availability_date:
                    type: string
                    format: date
                  courts:
                    type: array
                    items:
                      $ref: '#/components/schemas/CourtAvailability'
        '404':
          description: Club not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /subscriptions:
    post:
      summary: Create a new subscription
      description: Subscribe to notifications for court availability
      operationId: create_subscription
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubscriptionRequest'
      responses:
        '201':
          description: Subscription created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subscription'
        '400':
          description: Invalid request data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /subscriptions/{subscription_id}:
    get:
      summary: Get subscription details
      description: Retrieve details of a specific subscription
      operationId: get_subscription
      parameters:
        - name: subscription_id
          in: path
          required: true
          schema:
            type: string
          description: Unique identifier for the subscription
      responses:
        '200':
          description: Subscription details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subscription'
        '404':
          description: Subscription not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      summary: Cancel a subscription
      description: Cancel an existing subscription
      operationId: cancel_subscription
      parameters:
        - name: subscription_id
          in: path
          required: true
          schema:
            type: string
          description: Unique identifier for the subscription
      responses:
        '204':
          description: Subscription cancelled successfully
        '404':
          description: Subscription not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    TennisClub:
      type: object
      required:
        - id
        - name
        - location
        - booking_system
      properties:
        id:
          type: string
          description: Unique identifier for the club
          example: "club_123"
        name:
          type: string
          description: Name of the tennis club
          example: "Central Tennis Club"
        location:
          type: object
          properties:
            address:
              type: string
              example: "123 Tennis Street, City, State 12345"
            coordinates:
              type: object
              properties:
                lat:
                  type: number
                  format: float
                  example: 40.7128
                lng:
                  type: number
                  format: float
                  example: -74.0060
        booking_system:
          type: string
          description: Type of booking system used
          example: "courtreserve"
        courts:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                example: "court_1"
              name:
                type: string
                example: "Court 1"
              surface:
                type: string
                example: "hard"
              indoor:
                type: boolean
                example: false

    CourtAvailability:
      type: object
      required:
        - court_id
        - time_slots
      properties:
        court_id:
          type: string
          example: "court_1"
        court_name:
          type: string
          example: "Court 1"
        time_slots:
          type: array
          items:
            $ref: '#/components/schemas/TimeSlot'

    TimeSlot:
      type: object
      required:
        - start_time
        - end_time
        - available
      properties:
        start_time:
          type: string
          format: date-time
          example: "2024-01-15T10:00:00Z"
        end_time:
          type: string
          format: date-time
          example: "2024-01-15T11:00:00Z"
        available:
          type: boolean
          example: true
        price:
          type: number
          format: float
          example: 25.00
        currency:
          type: string
          example: "USD"

    SubscriptionRequest:
      type: object
      required:
        - email
        - club_id
        - preferred_times
      properties:
        email:
          type: string
          format: email
          example: "user@example.com"
        club_id:
          type: string
          example: "club_123"
        preferred_times:
          type: array
          items:
            type: object
            properties:
              day_of_week:
                type: integer
                minimum: 0
                maximum: 6
                example: 1
                description: "0=Monday, 6=Sunday"
              start_time:
                type: string
                pattern: "^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$"
                example: "10:00"
              end_time:
                type: string
                pattern: "^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$"
                example: "12:00"
        notification_preferences:
          type: object
          properties:
            email_enabled:
              type: boolean
              default: true
            sms_enabled:
              type: boolean
              default: false

    Subscription:
      type: object
      required:
        - id
        - email
        - club_id
        - status
        - created_at
      properties:
        id:
          type: string
          example: "sub_456"
        email:
          type: string
          format: email
          example: "user@example.com"
        club_id:
          type: string
          example: "club_123"
        preferred_times:
          type: array
          items:
            type: object
            properties:
              day_of_week:
                type: integer
                example: 1
              start_time:
                type: string
                example: "10:00"
              end_time:
                type: string
                example: "12:00"
        status:
          type: string
          enum: [active, paused, cancelled]
          example: "active"
        created_at:
          type: string
          format: date-time
          example: "2024-01-15T10:30:00Z"
        last_notification:
          type: string
          format: date-time
          example: "2024-01-15T09:15:00Z"

    Error:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          example: "validation_error"
        message:
          type: string
          example: "Invalid email format"
        details:
          type: object
          example: {"field": "email", "value": "invalid-email"}
