#!/usr/bin/env python3
"""
Generate Pydantic models from the OpenAPI specification.

Usage:
    poetry run generate          # via pyproject.toml script entry
    poetry run python -m scripts.generate   # direct module execution

The generated models are written to app/generated/models.py and should NOT
be edited by hand – any manual changes will be overwritten on the next run.
"""

import subprocess
import sys
from pathlib import Path

# Resolve paths relative to the project root (parent of scripts/)
PROJECT_ROOT = Path(__file__).resolve().parent.parent
OPENAPI_SPEC = PROJECT_ROOT / "openapi.yaml"
OUTPUT_DIR = PROJECT_ROOT / "app" / "generated"
OUTPUT_FILE = OUTPUT_DIR / "models.py"


def main() -> None:
    """Run datamodel-code-generator to produce Pydantic v2 models."""
    if not OPENAPI_SPEC.exists():
        print(f"ERROR: OpenAPI spec not found at {OPENAPI_SPEC}", file=sys.stderr)
        sys.exit(1)

    # Ensure output directory exists
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    # Create __init__.py for the generated package
    init_file = OUTPUT_DIR / "__init__.py"
    if not init_file.exists():
        init_file.write_text('# Auto-generated package – do not edit\n')

    cmd = [
        sys.executable, "-m", "datamodel_code_generator",
        "--input", str(OPENAPI_SPEC),
        "--input-file-type", "openapi",
        "--output", str(OUTPUT_FILE),
        # Pydantic v2 mode
        "--output-model-type", "pydantic_v2.BaseModel",
        # Use standard-library Enum
        "--enum-field-as-literal", "all",
        # Use Annotated style for Field() metadata
        "--use-annotated",
        # Use standard library types (datetime, UUID, etc.)
        "--use-standard-collections",
        "--use-union-operator",
        # Target Python 3.12
        "--target-python-version", "3.12",
        # Collapse single allOf references
        "--collapse-root-models",
        # Keep None defaults on nullable fields so they're truly optional
        # (do NOT use --strip-default-none)
    ]

    print(f"Generating models from {OPENAPI_SPEC} → {OUTPUT_FILE}")
    result = subprocess.run(cmd, capture_output=True, text=True)

    if result.returncode != 0:
        print("STDERR:", result.stderr, file=sys.stderr)
        print("STDOUT:", result.stdout)
        sys.exit(result.returncode)

    # Add a header comment to the generated file
    generated = OUTPUT_FILE.read_text()
    header = (
        '# AUTO-GENERATED by datamodel-code-generator from openapi.yaml\n'
        '# DO NOT EDIT THIS FILE MANUALLY – run `poetry run generate` instead.\n\n'
    )
    if not generated.startswith("# AUTO-GENERATED"):
        OUTPUT_FILE.write_text(header + generated)

    print(f"✓ Models generated successfully at {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
